In [31]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier 

In [3]:
df = pd.read_csv("dump2.csv")
df.head(5)

id        box_id      device_type false_character  hold_for key_pressed  \
0  902  #text-area-1  Computer/Laptop               f       754       Shift   
1  903  #text-area-1  Computer/Laptop               f        63           h   
2  904  #text-area-1  Computer/Laptop               f        80           i   
3  905  #text-area-1  Computer/Laptop               f        86           s   
4  906  #text-area-1  Computer/Laptop               f        72               

   location  long_pressed_equivalent   name  platform  pressed_after  \
0        16                        2  Kedar  MacIntel              0   
1        72                        1  Kedar  MacIntel            457   
2        73                        1  Kedar  MacIntel            105   
3        83                        1  Kedar  MacIntel             19   
4        32                        1  Kedar  MacIntel             54   

       timestamp                               user_id  
0  1584257309690  ef70b84c-be3d-434b-9cbe-55a19ce557a0  
1  1584257310901  ef70b84c-be3d-434b-9cbe-55a19ce557a0  
2  1584257311070  ef70b84c-be3d-434b-9cbe-55a19ce557a0  
3  1584257311169  ef70b84c-be3d-434b-9cbe-55a19ce557a0  
4  1584257311309  ef70b84c-be3d-434b-9cbe-55a19ce557a0

In [5]:
df.describe()

id     hold_for     location  long_pressed_equivalent  \
count  5066.000000  5066.000000  5066.000000              5066.000000   
mean   4504.363798    86.779510    67.716147                 1.104816   
std    2169.199841    50.219924    30.179777                 0.330527   
min     902.000000     2.000000     8.000000                 1.000000   
25%    2205.250000    64.000000    65.000000                 1.000000   
50%    5132.500000    79.000000    72.000000                 1.000000   
75%    6398.750000    98.000000    82.000000                 1.000000   
max    7696.000000  1518.000000   191.000000                 8.000000   

       pressed_after     timestamp  
count    5066.000000  5.066000e+03  
mean      147.732925  1.584719e+12  
std       177.312726  3.724015e+08  
min         0.000000  1.584257e+12  
25%        52.000000  1.584560e+12  
50%        99.000000  1.584662e+12  
75%       170.000000  1.584662e+12  
max      3199.000000  1.585438e+12

In [7]:
df['name'].value_counts()

Kedar             2542
Vikas Ramaneti     945
Sope Ogundipe      810
Kunal Sonar        769
Name: name, dtype: int64

In [9]:
labelEncoder = preprocessing.LabelEncoder()
df['false_character'] = labelEncoder.fit_transform(df['false_character'])
false_character_map = {labelEncoder.classes_[i] : i for i in range(len(labelEncoder.classes_))}
df['name'] = labelEncoder.fit_transform(df['name'])
name_map = {labelEncoder.classes_[i] : i for i in range(len(labelEncoder.classes_))}
df['box_id'] = labelEncoder.fit_transform(df['box_id'])
box_map = {labelEncoder.classes_[i] : i for i in range(len(labelEncoder.classes_))}
df.head(5)

id  box_id      device_type  false_character  hold_for key_pressed  \
0  902       0  Computer/Laptop                0       754       Shift   
1  903       0  Computer/Laptop                0        63           h   
2  904       0  Computer/Laptop                0        80           i   
3  905       0  Computer/Laptop                0        86           s   
4  906       0  Computer/Laptop                0        72               

   location  long_pressed_equivalent  name  platform  pressed_after  \
0        16                        2     0  MacIntel              0   
1        72                        1     0  MacIntel            457   
2        73                        1     0  MacIntel            105   
3        83                        1     0  MacIntel             19   
4        32                        1     0  MacIntel             54   

       timestamp                               user_id  
0  1584257309690  ef70b84c-be3d-434b-9cbe-55a19ce557a0  
1  1584257310901  ef70b84c-be3d-434b-9cbe-55a19ce557a0  
2  1584257311070  ef70b84c-be3d-434b-9cbe-55a19ce557a0  
3  1584257311169  ef70b84c-be3d-434b-9cbe-55a19ce557a0  
4  1584257311309  ef70b84c-be3d-434b-9cbe-55a19ce557a0

In [10]:
false_character_map, name_map, box_map

({'f': 0, 't': 1},
 {'Kedar': 0, 'Kunal Sonar': 1, 'Sope Ogundipe': 2, 'Vikas Ramaneti': 3},
 {'#text-area-1': 0,
  '#text-area-2': 1,
  '#text-area-3': 2,
  '#text-area-test': 3})

In [11]:
df_reduced = df[['name','false_character','hold_for','location','long_pressed_equivalent','pressed_after']]
df_reduced['name'] = np.where(df_reduced['name'] != 0, 1, 0)
df_reduced.head(5)

C:\Users\sopeo\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


name  false_character  hold_for  location  long_pressed_equivalent  \
0     0                0       754        16                        2   
1     0                0        63        72                        1   
2     0                0        80        73                        1   
3     0                0        86        83                        1   
4     0                0        72        32                        1   

   pressed_after  
0              0  
1            457  
2            105  
3             19  
4             54

In [13]:
df_reduced['name'].value_counts()

0    2542
1    2524
Name: name, dtype: int64

In [15]:
X_train, X_test, y_train, y_test = train_test_split(df_reduced.iloc[:,1:], df_reduced.iloc[:,0], test_size=0.2, stratify=df_reduced.iloc[:,0], random_state=109)

In [16]:
grouped = df_reduced.groupby('name')
balance_df = grouped.apply(lambda x : x.sample(grouped.size().min())).reset_index(drop=True)
balance_df['name'].value_counts()

1    2524
0    2524
Name: name, dtype: int64

In [17]:
balance_df[['name','false_character','long_pressed_equivalent','hold_for']].groupby(['name','false_character','long_pressed_equivalent']).count()

hold_for
name false_character long_pressed_equivalent          
0    0               1                            2127
                     2                             244
                     3                               1
     1               1                             141
                     2                              11
1    0               1                            2041
                     2                             247
                     3                               1
                     8                               1
     1               1                             224
                     2                               8
                     5                               1
                     6                               1

In [18]:
X_train_bal, X_test_bal, y_train_bal, y_test_bal = train_test_split(balance_df.iloc[:,1:], balance_df.iloc[:,0], test_size=0.2, stratify=balance_df.iloc[:,0] ,random_state=10)

### SVM Binary Classification on Unbalanced Data

In [ ]:
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train, y_train) 
svm_predictions = svm_model_linear.predict(X_test) 

In [46]:
# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test, y_test) 
print("Accuracy : ", (accuracy*100).round(3))

Accuracy :  54.536


In [47]:
# creating a confusion matrix 
cm = confusion_matrix(y_test, svm_predictions) 
print('Confusion Matrix :')
print(cm)

Confusion Matrix :
[[429  80]
 [381 124]]


In [48]:
print('Classification Report : ')
print(classification_report(y_test, svm_predictions))

Classification Report : 
              precision    recall  f1-score   support

           0       0.53      0.84      0.65       509
           1       0.61      0.25      0.35       505

    accuracy                           0.55      1014
   macro avg       0.57      0.54      0.50      1014
weighted avg       0.57      0.55      0.50      1014



### SVM Binary Classification on Balanced Data

In [49]:
svm_model_linear = SVC(kernel = 'linear', C = 1).fit(X_train_bal, y_train_bal) 
svm_predictions = svm_model_linear.predict(X_test_bal) 

In [52]:
# model accuracy for X_test   
accuracy = svm_model_linear.score(X_test_bal, y_test_bal) 
print("Accuracy : ", (accuracy*100).round(3))

Accuracy :  52.871


In [53]:
# creating a confusion matrix 
cm = confusion_matrix(y_test_bal, svm_predictions) 
print('Confusion Matrix :')
print(cm)

Confusion Matrix :
[[433  72]
 [404 101]]


In [54]:
print('Classification Report : ')
print(classification_report(y_test_bal, svm_predictions))

Classification Report : 
              precision    recall  f1-score   support

           0       0.52      0.86      0.65       505
           1       0.58      0.20      0.30       505

    accuracy                           0.53      1010
   macro avg       0.55      0.53      0.47      1010
weighted avg       0.55      0.53      0.47      1010



### KNN Binary Classification on Unbalanced Data

In [19]:
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train, y_train) 

In [22]:
# accuracy on X_test 
accuracy = knn.score(X_test, y_test) 
print("Accuracy : ", (accuracy*100).round(3))

Accuracy :  65.976


In [24]:
# creating a confusion matrix 
knn_predictions = knn.predict(X_test)  
cm = confusion_matrix(y_test, knn_predictions) 

In [27]:
print('Confusion Matrix :')
print(cm)

Confusion Matrix :
[[332 177]
 [168 337]]


In [35]:
print('Classification Report : ')
print(classification_report(y_test, knn_predictions))

Classification Report : 
              precision    recall  f1-score   support

           0       0.66      0.65      0.66       509
           1       0.66      0.67      0.66       505

    accuracy                           0.66      1014
   macro avg       0.66      0.66      0.66      1014
weighted avg       0.66      0.66      0.66      1014



## KNN Binary Classification on Balanced Data

In [36]:
knn = KNeighborsClassifier(n_neighbors = 7).fit(X_train_bal, y_train_bal) 

In [37]:
# accuracy on X_test_balanced 
accuracy = knn.score(X_test_bal, y_test_bal) 
print("Accuracy : ", (accuracy*100).round(3))

Accuracy :  65.644


In [39]:
# creating a confusion matrix 
knn_predictions = knn.predict(X_test_bal)  
cm = confusion_matrix(y_test_bal, knn_predictions) 

In [40]:
print('Confusion Matrix :')
print(cm)

Confusion Matrix :
[[354 151]
 [196 309]]


In [41]:
print('Classification Report : ')
print(classification_report(y_test_bal, knn_predictions))

Classification Report : 
              precision    recall  f1-score   support

           0       0.64      0.70      0.67       505
           1       0.67      0.61      0.64       505

    accuracy                           0.66      1010
   macro avg       0.66      0.66      0.66      1010
weighted avg       0.66      0.66      0.66      1010

